version: "3.4"

services:
  synapse:
    container_name: "synapse"
    image: "matrixdotorg/synapse:latest-py3"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:8008:8008"
        #- "127.0.0.1:8448:8448"
    volumes:
      - "/apps/synapse/data/:/data/"
    depends_on:
      - db
  db:
    image: docker.io/postgres:10-alpine
    container_name: synapse_db
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=G6KcqAb8mqr7mWTZWtN82Wuj
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /apps/synapse/dbdata:/var/lib/postgresql/data
